# Generated by Django 5.0.6 on 2024-07-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_options_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room_str',
            field=models.CharField(default='room1', max_length=255),
        ),
    ]
